# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: daily
      time: "05:30" # UTC
    open-pull-requests-limit: 20
    rebase-strategy: auto
    versioning-strategy: increase-if-necessary # keeps Cargo.toml bumps minimal; updates Cargo.lock as needed
    labels: ["dependencies", "rust"]
    groups:
      rust-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      rust-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/vacs-client"
    schedule:
      interval: daily
      time: "06:00" # UTC
    open-pull-requests-limit: 20
    rebase-strategy: auto
    versioning-strategy: increase
    labels: ["dependencies", "node"]
    groups:
      npm-patch-minor:
        patterns: ["*"]
        update-types: ["patch", "minor"]
      npm-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "06:30" # UTC
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: ["dependencies"]
    groups:
      gha-all:
        patterns: ["*"]

  - package-ecosystem: docker
    directory: "/vacs-server"
    schedule:
      interval: weekly
      day: saturday
      time: "07:00" # UTC
    open-pull-requests-limit: 10
    rebase-strategy: auto
    labels: ["dependencies"]
