[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc"
]
all-features = false
no-default-features = false
features = ["test-utils"]

[advisories]
ignore = [
    { id = "RUSTSEC-2024-0413", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0416", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0057", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0412", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0418", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0411", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0417", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0414", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0429", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0415", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0420", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0419", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0370", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0081", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0075", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0080", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0100", reason = "tauri dependency" },
    { id = "RUSTSEC-2025-0098", reason = "tauri dependency" },
    { id = "RUSTSEC-2024-0436", reason = "tower-sessions-redis-store dependency" },
]

[licenses]
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-3-Clause",
    "ISC",
    "MIT",
    "MPL-2.0",
    "Unicode-3.0",
]
exceptions = [
    { allow = ["Zlib"], crate = "foldhash" },
    { allow = ["CC0-1.0"], crate = "tiny-keccak" },
    { allow = ["CDLA-Permissive-2.0"], crate = "webpki-roots" },
]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true

[sources]
unknown-registry = "warn"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[sources.allow-org]
github = [
    "tauri-apps"
]
