[package]
name = "vacs-server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axum = { version = "0.8.4", features = ["ws"] }
futures-util = "0.3.31"
tokio = { workspace = true }
tower-http = { version = "0.6.5", features = ["trace", "timeout"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
vacs-shared = { path = "../vacs-shared" }
anyhow = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
directories = { workspace = true }

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = { workspace = true }
test-log = { workspace = true }
