[package]
name = "vacs-server"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
axum = { version = "0.8.4", features = ["ws"] }
futures-util = "0.3.31"
tokio = { workspace = true }
tower-http = { version = "0.6.5", features = ["trace", "timeout"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
tokio-tungstenite = { workspace = true }
serde = { workspace = true }
config = { workspace = true }
directories = { workspace = true }
vacs-core = { path = "../vacs-core", features = ["server"] }

[lints]
workspace = true

[dev-dependencies]
pretty_assertions = { workspace = true, features = ["unstable"] }
test-log = { workspace = true }
