[package]
name = "vacs-shared"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]

[dependencies]
serde = { workspace = true }
serde_json = "1.0.140"

[lints]
workspace = true