[package]
name = "vacs-client"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "vacs_client_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { workspace = true, features = [] }

[dependencies]
anyhow = { workspace = true }
tauri = { workspace = true, features = [] }
tauri-plugin-opener = { workspace = true }
tokio = { workspace = true }
vacs-signaling = { workspace = true }
vacs-vatsim = { workspace = true, features = ["oauth"] }
