name: CI â€¢ Node

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'vacs-client/frontend/**'
      - '!vacs-client/frontend/icons/**'
      - '.github/workflows/ci-node.yml'
  push:
    branches: [ main ]
    paths:
      - 'vacs-client/frontend/**'
      - '!vacs-client/frontend/icons/**'
      - '.github/workflows/ci-node.yml'

permissions:
  contents: read

concurrency:
  group: node-ci-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  check:
    if: >
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node (LTS)
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: |
            vacs-client/package-lock.json
            vacs-client/frontend/package-lock.json

      - name: Install dependencies
        working-directory: vacs-client
        run: npm ci

      - name: Typecheck
        working-directory: vacs-client
        run: npm run -w frontend typecheck

      - name: Lint
        working-directory: vacs-client
        run: npm run -w frontend lint